# 網站基本設定
title: SOSI 產品文件中心
email: rica@yourdomain.com
description: >-
  這裡是 SOSI 的產品操作與安全審計手冊，提供最詳細的教學指南。

# 修正 404 錯誤的核心設定 (務必檢查)
baseurl: "/SOSI" 
url: "https://rica-star.github.io"

# 社群帳號設定 (刪除預設值可清空首頁頁尾)
twitter_username: 
github_username: rica-star

# 編譯設定
theme: minima
plugins:
  - jekyll-feed

# 排除不需要處理的檔案
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/